import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Card, CardGroup, Container } from "react-bootstrap";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>

        <CardGroup>
          <Card>
            <Card.Body>
              <Card.Title>Documentation &rarr;</Card.Title>
              <Card.Link href="https://nextjs.org/docs">
                Find in-depth information about Next.js features and API.
              </Card.Link>
            </Card.Body>
          </Card>

          <Card>
            <Card.Body>
              <Card.Title>Learn &rarr;</Card.Title>
              <Card.Link href="https://nextjs.org/learn">
                Learn about Next.js in an interactive course with quizzes!
              </Card.Link>
            </Card.Body>
          </Card>

          <Card>
            <Card.Title>Examples &rarr;</Card.Title>
            <Card.Body>
              <Card.Link href="https://github.com/vercel/next.js/tree/canary/examples">
                Discover and deploy boilerplate example Next.js projects.
              </Card.Link>
            </Card.Body>
          </Card>

          <Card>
            <Card.Title>Deploy &rarr;</Card.Title>
            <Card.Body>
              <Card.Link href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
                Instantly deploy your Next.js site to a public URL with Vercel.
              </Card.Link>
            </Card.Body>
          </Card>
        </CardGroup>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
  );
};

export default Home;
